name: wellcare_checkout
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  linter: ^1.3.0

flutter:
